language:  csharp
mono: none
dotnet: 3.1

env: 
    - PROJECT="AnonymousPipe"
    - PROJECT="Devices"
    - PROJECT="DiningPhilosophersBare"
    - PROJECT="MyProcessSample" 
    - PROJECT="NamedPipe"
    - PROJECT="NetMQExample"
    - PROJECT="Peterson"
    - PROJECT="ProcessStartExample"
    - PROJECT="ProducerConsumerBare"
    - PROJECT="ProducerConsumerLock"
    - PROJECT="ProducerConsumerMutex"
    - PROJECT="Seitenersetzung"    
    - PROJECT="Threads"

script:
    - cd $PROJECT
    - cd $PROJECT
    - dotnet build
    - cd ..
    - | 
        if [[ -d "$PROJECT.Tests" ]]
        then 
          cd ${PROJECT}.Tests
          dotnet test
          cd ..
        fi
    - cd ..
    - | 
        if [[ -d "$PROJECT.Core.Tests" ]]
        then 
          cd ${PROJECT}.Tests
          dotnet test
          cd ..
        fi
    - cd ..
    - | 
        if [[ -d "$PROJECT.Infrastructure.Tests" ]]
        then 
          cd ${PROJECT}.Tests
          dotnet test
          cd ..
        fi
    - cd ..
